# Generated by Django 4.2.15 on 2024-09-11 21:56

import django.core.validators
from django.db import migrations, models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Benz', 'Benz'), ('BMW', 'BMW'), ('Porche', 'Porche')], max_length=20)),
                ('year_built', models.DateField()),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='price_must_be_greater_than_zero'),
        ),
    ]
