# Generated by Django 5.1.1 on 2024-09-12 21:20

import django.core.validators
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Benz', 'Benz'), ('BMW', 'BMW'), ('Porche', 'Porche')], max_length=20)),
                ('year_built', models.DateField()),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
